apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.1.2
    helm:
      releaseName: monitoring
      valuesObject:
        defaultRules:
          rules:
            etcd: false
            kubeControllerManager: false
            kubeProxy: false
            kubeSchedulerAlerting: false
            kubeSchedulerRecording: false

        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeProxy:
          enabled: false
        kubeScheduler:
          enabled: false

        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.home.internal
            tls:
              - hosts:
                  - grafana.home.internal
            path: /
            pathType: Prefix
          persistence:
            enabled: true
            type: sts
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            size: 2Gi

        prometheus:
          prometheusSpec:
            retention: 7d
            retentionSize: 8GB
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 2Gi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: monitoring-grafana
      namespace: monitoring
      jsonPointers:
        - /data/admin-password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
