apiVersion: v1
kind: Secret
metadata:
    name: homepage-adguard
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ED+zAmE=,iv:L+jQceZ6C4FWUw4sibFNEdCOlPO99IueksnZrdXZJhI=,tag:HBoJb9g1Ue5GZROCC7YCrg==,type:str]
    password: ENC[AES256_GCM,data:BjvjqBibZZDu579ptAEISA==,iv:XhrMwqAef/A8CbDwjRxfs9vx9yu3WpOj6BWsZp9iBj0=,tag:/WQSjcFgEyUnSvvwiAVyHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc2lxWGkwRmFiNlNSaWdH
            ZEEvcHZ2ODduODFFZ3R3Qlg1eXZ1MG9CZkVzCjVqWXFjU1lFNjhIa01yZzZBZ082
            R0sxdEFFV2xQMmFiWjRoellSS2ppOUUKLS0tIE9xSldTZ2dCQmd4VjNkQmNvOXdj
            NHZ2MlFoVklROWF2Z2Q1T3ptWjhMU00KxIB66Cacl6KGtKZbBaNV6il8aPM21fbO
            Yf0SRh22fdtkbvHLr8i2rnYHi1aGlEx2k4ld5O1cKgsJiPmFmV9Nkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jen8prarmxledprxuwyxjcwlx84xklyp7pulvqrjf7ms04ll3pzqnjuk37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T21:34:52Z"
    mac: ENC[AES256_GCM,data:hJn60/hDeRLOH0GhVGiPWu/9Z5rPw9ovoc5Z+vuo80QYUb32qGkoFSiJzUEAxQ1OkzVB59W5s4n76yGxcDt591yO7tm4gOHezG6efiX/gvU/dhSaudyT5XRMy+d9581ClzKRwha75pz/QG9/ukamBeFbf9bFi9VApXKCI/jvqfE=,iv:8AVDVcLfVc8DwQaFXDkx14w35UQaY5fWYpZcFpJEHNM=,tag:lEDvUxnGwBnheoxSNHojXQ==,type:str]
    version: 3.13.3
