apiVersion: v1
kind: Secret
metadata:
    name: homepage-adguard
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:d0A9jBg=,iv:1ypmbl8YOn/KKX/KEiNWVPOP//F07EVLBKdZ+y/NSjw=,tag:HA5WSpgAyq0F1ipWHKI+Yg==,type:str]
    password: ENC[AES256_GCM,data:Atw24ZKtZvkfvRJWRbw=,iv:v6oq/tbn5Pav3kn7y7NxX32a1ZTbtVMQN4EqNWK8na4=,tag:eSlKTo7poULW8Sb8vvHlGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVm5qaGFEelZWVUVIL1V0
            OElLdFZrOWpuanRoVFVMYk1uZnFPbDZzbUdBCkV6MVQ4OTEzZzJSRjRSMThQQnpM
            cEt4VmhEVkRxdWFUSjVpZERPa28yUk0KLS0tIFRnZnNDR0ROUW1RM2Q0QmlTTTJn
            NDBIVldNaU5ZMjVXa2Rad1ZFd3llVWcKqT/heHxzhHJQpSR7hhVM2LK/6sW4Cv7m
            /xd5A4eorl4QGay8c3HKGBWn4vp5E+8lSNEq9Ef4Jovlx5ymllEjyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jen8prarmxledprxuwyxjcwlx84xklyp7pulvqrjf7ms04ll3pzqnjuk37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T21:04:07Z"
    mac: ENC[AES256_GCM,data:SrJ3qqjF6VsCYDLAf4BrKgl+WX7vWFZuXE8HMZ3NP7wmXUj4njEy2cMhLdQAUSPc4CrNQoadL64yZDG6TzSQJTcypCHVxHHhfOH32M75fsxhJ54NXg+bqFPxDKx8emaf8nouEQzjTIK2jklaIH93iCKZJ7B5E56k28tHn5k6kAo=,iv:jyT0zJe+1/UTuMBBQvvib6vpgEzmA4FPoU1qiNxGcxs=,tag:H0GFigu8qtyo0B8Uwpad5w==,type:str]
    version: 3.13.3
