apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - homepage-clusterrole.yaml
  - homepage-deployment.yaml
  - homepage-service.yaml
  - homepage-cm.yaml
  - homepage-ingress.yaml
  - ServiceAccount.yaml
