apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/argocd.yaml
  - coredns/coredns.yaml
  - externalService/externalService.yaml
  - monitoring/monitoring.yaml
  - traefik/traefik.yaml
  - cert-manager/cert-manager.yaml
